services:
  hnsttp:
    build: .
    container_name: pytorch-research
    privileged: true
    pid: host
    shm_size: '8gb'

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    volumes:
      - ./:/workspace

    ports:
      - "8888:8888"

    stdin_open: true
    tty: true
    restart: unless-stopped
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''