services:
  scr-tpp:
    build: .
    image: scr-tpp:latest
    container_name: scr-tpp
    shm_size: '16gb'
    gpus: all
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      PYTHONPATH: /workspace
      OMP_NUM_THREADS: "12"
      MKL_NUM_THREADS: "12"
      OPENBLAS_NUM_THREADS: "12"
      NUMEXPR_NUM_THREADS: "12"
    stdin_open: true
    tty: true
    command: bash
