settings:
  output_file: "./data/synthetic_data.pkl"
  num_samples: 10000      
  time_horizon: 500.0      
  base_intensities: 
    0: 0.2
    1: 0.02
    2: 0.2
    3: 0.2
    4: 0.02

rules:
  - rule_id: 1
    target: 1             
    base_prob: 0.8        
    sources:              
      0:                  
        mu: 2.0           
        std: 0.5          

  - rule_id: 2
    target: 4
    base_prob: 0.9
    sources:
      2: {mu: 3.0, std: 0.5}  
      3: {mu: 1.0, std: 0.2} 


interactions:
  - src: 1                
    tgt: 2                
    factor: 0.1           
    beta: 0.5             